param([string]$Workspace = (Resolve-Path "$PSScriptRoot/../..").Path)
$ErrorActionPreference = 'Stop'
$outDir = Join-Path $Workspace 'research/inventories'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$configs = @(
    @{ Name = 'frcsoftware'; Repo = 'frcsoftware/frcsoftware.org'; Site = 'https://frcsoftware.org' },
    @{ Name = 'frcdesign'; Repo = 'frcdesign/FRCDesign.org'; Site = 'https://frcdesign.org' }
)
foreach ($config in $configs) {
    $root = Join-Path $Workspace ".research-cache/$($config.Name)"
    $commit = (git -C $root rev-parse HEAD).Trim()
    $docs = Join-Path $root 'src/content/docs'
    $pages = @(Get-ChildItem -LiteralPath $docs -Recurse -File -Filter '*.mdx' | Sort-Object FullName | ForEach-Object {
        $body = Get-Content -LiteralPath $_.FullName -Raw
        $path = [IO.Path]::GetRelativePath($root, $_.FullName).Replace('\', '/')
        $slug = $path -replace '^src/content/docs/', '' -replace '\.mdx$', '' -replace '(^|/)index$', ''
        $title = [regex]::Match($body, '(?m)^title:\s*(.+)$').Groups[1].Value.Trim().Trim('"', "'")
        $headings = @([regex]::Matches($body, '(?m)^#{1,6}\s+(.+)$') | ForEach-Object { $_.Groups[1].Value.Trim() })
        $status = @([regex]::Matches($body, '(?im)^.*(?:type="wip"|hasn.t been written|still in development|TODO|TBD).*$') | ForEach-Object { $_.Value.Trim() })
        [ordered]@{
            path = $path
            title = $title
            url_candidate = if ($slug.Trim('/')) { "$($config.Site)/$($slug.Trim('/'))/" } else { "$($config.Site)/" }
            source = "https://github.com/$($config.Repo)/blob/$commit/$path"
            sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLower()
            words_approx = ([regex]::Matches($body, '\S+')).Count
            headings = $headings
            status_markers = $status
            coverage = 'indexed; detailed review only where named in coverage.md'
        }
    })
    $manifest = [ordered]@{ name = $config.Name; repository = $config.Repo; commit = $commit; retrieved = '2026-09-21 America/Los_Angeles'; page_count = $pages.Count; pages = $pages }
    $manifest | ConvertTo-Json -Depth 10 | Set-Content -Encoding utf8 (Join-Path $outDir "$($config.Name).json")
    $lines = @("# $($config.Name) page inventory", '', "Revision: ``$commit``. $($pages.Count) MDX files. Generated by ``research/tools/index-sources.ps1``.", '', 'Complete source-file inventory, not a claim that every page or external asset has been fully reviewed. Source links are authoritative; live URL candidates are inferred from filenames and may differ due to slug overrides.', '', '| Page | Source path | WIP/TODO markers |', '|---|---|---|')
    foreach ($page in $pages) {
        $safeTitle = $page.title.Replace('|', '\|')
        $lines += "| [$safeTitle]($($page.source)) | ``$($page.path)`` | $($page.status_markers.Count) |"
    }
    $lines | Set-Content -Encoding utf8 (Join-Path $outDir "$($config.Name).md")
    [pscustomobject]@{ Site = $config.Name; Commit = $commit; Pages = $pages.Count; Words = ($pages | ForEach-Object { $_.words_approx } | Measure-Object -Sum).Sum }
}
